Atualização DDL
projetoKhali/api3 pull request #117
Opened 2023-09-30 20:51 UTC by JhonatanLop

# 🏅 Comentários adicionais <br>  
`Algo mais que gostaria de comentar com a equipe a respeito da entrega dessa tarefa?`

-  adicionei algumas constraints e concertei a auto-relação da tabela appontments para atualização de apontamentos

<br>

2023-09-30 23:22 UTC, paulo-granthon requested changes

2023-09-30 23:22 UTC, paulo-granthon commented on api/sql/ddl/table.sql
>      prt_id serial primary key,
`prt_id` está duplicado

2023-09-30 23:22 UTC, paulo-granthon commented on api/sql/ddl/table.sql
>      clt_id serial primary key,
`clt_id` está duplicado

2023-09-30 23:22 UTC, paulo-granthon commented on api/sql/ddl/table.sql
> +    code int unique not null,
`rc_id` e `code` estão duplicados

2023-09-30 23:22 UTC, paulo-granthon commented on api/sql/ddl/table.sql
> +    association_date timestamp default now(),
poderia ser `insert_date` para manter a consistencia com as outras tabelas

2023-09-30 23:22 UTC, paulo-granthon commented on api/sql/ddl/table.sql
> +    (apt_updt_id) references appointments(apt_id)
constraint `appointment_updt` poderia ser `apt_updt_idfk` para manter a consistencia com as outras tabelas

2023-09-30 23:23 UTC, paulo-granthon commented
mudei a base do pr para `develop`

2023-09-30 23:26 UTC, paulo-granthon commented
also, falta um `from users;` na view `vw_users`, já poderia incluir nesse PR

2023-10-01 21:12 UTC, JhonatanLop commented on api/sql/ddl/table.sql
> +    (apt_updt_id) references appointments(apt_id)
chatão hein zé

2023-10-05 00:25 UTC, paulo-granthon approved these changes
muito bom :+1:

2023-10-08 20:22 UTC, Incivius approved these changes

2023-10-08 20:36 UTC, merged