Feat: Criptografia
projetoKhali/api3 pull request #126
Opened 2023-10-04 22:58 UTC by JhonatanLop

# 🥳 Conclusão de tarefa <br>  
`Insira o #ID do(s) Issue(s) que essa entrega conclui no seguinte formato: "resolve #ID"`  

- resolve #90

<br>

# 🐞Bugs <br>  
`Essa entrega inclui algum bug não-solucionado? Cite-o(s)`

Não é possível executar testes com JUnit, mas isso não impede a funcionalidade.

<br>

2023-10-04 23:18 UTC, taniacruzz approved these changes

2023-10-04 23:26 UTC, paulo-granthon requested changes

2023-10-04 23:26 UTC, paulo-granthon commented on api/src/main/java/com/khali/api3/domain/user/Cryptography.java
> +    }
Não há necessidade de haver um método main.
Esse código pode ser movido para um unit test.
```suggestion
```

2023-10-04 23:26 UTC, paulo-granthon commented on api/src/main/resources/application.properties
arquivo `application.properties` não deve ser commitado

2023-10-08 20:14 UTC, Incivius approved these changes

2023-10-08 23:00 UTC, paulo-granthon approved these changes

2023-10-15 19:55 UTC, merged