User_controller
projetoKhali/api3 pull request #131
Opened 2023-10-06 03:56 UTC by JhonatanLop

# 🥳 Conclusão de tarefa <br>  
`Insira o #ID do(s) Issue(s) que essa entrega conclui no seguinte formato: "resolve #ID"`  

- resolve #91

<br>

# 🚀 Extras <br>  
`Essa entrega inclui alguma feature extra concluída ou em progress? Cite-a(s)`

 - criei também o método para reativar usuário

<br>

2023-10-06 17:12 UTC, paulo-granthon requested changes
O branch `user_controller` possui base no commit 6e700a9 e está desatualizado.
Sempre ao reaproveitar branches existes para a conclusão de novas tarefas após o fechamento do PR anteriormente associado ao branch, deve ser feita uma sincronização com o estado atual do branch `develop` ou `main`.
Recomendo utilizar a visualização proporcionada [pelo gráfico `network` da aba `insights`](https://github.com/projetoKhali/api3/network) para melhor acompanhamento do histórico dos branches

2023-10-06 17:12 UTC, paulo-granthon commented on api/sql/ddl/table.sql
> +    user_type varchar,
Já que sugere não utilizar o enum no banco de dados, sugiro que utilize integer para representar o tipo do usuário:
0 - employee
1 - manager
2 - adm

2023-10-06 17:14 UTC, paulo-granthon commented on api/sql/ddl/table.sql
> +    user_type varchar,
also, deve ser considerada a interação com o spring-boot.
Ao mudar o tipo de dado no banco, deve-se garantir a permanencia ou restauração da compatibilidade entre ambos.

2023-10-07 00:07 UTC, JhonatanLop commented on api/sql/ddl/table.sql
> +    user_type varchar,
a fim de minimizar trabalho desnecessário, irei permanecer com o tipo varchar visto que o mesmo funciona perfeitamente sem qualquer alteração no java

2023-10-07 00:14 UTC, paulo-granthon requested changes

2023-10-07 00:14 UTC, paulo-granthon commented on api/sql/ddl/table.sql
> +create table if not exists user(
```suggestion
create table if not exists users (
```

2023-10-07 00:19 UTC, paulo-granthon requested changes

2023-10-07 00:19 UTC, paulo-granthon commented on api/src/main/resources/application.properties
> +<<<<<<< HEAD
artefatos do merge no arquivo

2023-10-07 00:33 UTC, paulo-granthon approved these changes
nice

2023-10-08 20:07 UTC, Incivius approved these changes

2023-10-08 20:07 UTC, merged