Project - Entrega final
projetoKhali/api3 pull request #143
Opened 2023-10-12 17:25 UTC by Incivius

# 🥳 Conclusão de tarefa <br>  
- resolve #94 #
- resolve #135
- resolve #100
- resolve #101
- resolve #102
- resolve #103
- resolve #104
- resolve #105
- resolve #121
- resolve #122
- resolve #123
- resolve #124
- resolve #125
<br>

2023-10-12 17:48 UTC, taniacruzz reviewed
inserir ";" após a criação da tabela de projetos, no arquivo DDL

2023-10-12 18:30 UTC, paulo-granthon requested changes

2023-10-12 18:30 UTC, paulo-granthon commented on api/sql/ddl/table.sql
> +)
Como a @taniacruzz havia mencionado anteriormente
```suggestion
);
```

2023-10-12 18:30 UTC, paulo-granthon commented on api/sql/ddl/table.sql
> +    active bool default true,
Como não usaremos mais a boolean `active`, já poderíamos desconsiderá-la nessa entrega
```suggestion
```

2023-10-12 18:30 UTC, paulo-granthon commented on api/src/main/java/com/khali/api3/controllers/ProjectController.java
> +    @GetMapping("/all")
Por questão de consistência, poderíamos deixar essa `GetMapping` como padrão, sem a sub rota `/all`
```suggestion
    @GetMapping()
```

2023-10-12 18:30 UTC, paulo-granthon commented on api/src/main/java/com/khali/api3/domain/project/Project.java
> +    private boolean active;
Assim como um dos comentários anteriores:
Já que estaremos removendo a boolean `active` das outras entidades, já poderíamos desconsiderá-la na inclusão da nova classe
```suggestion
```

2023-10-12 18:30 UTC, paulo-granthon commented on api/src/main/java/com/khali/api3/repositories/ProjectRepository.java
> +
```suggestion
```

2023-10-12 18:30 UTC, paulo-granthon commented on api/src/main/java/com/khali/api3/repositories/ProjectRepository.java
> +    int insertProject(@Param("name") String name, @Param("description") String description);
Esse padrão está sendo utilizado em outros locais do código? Há necessidade de utilizar `nativeQuery` aqui?

2023-10-12 18:30 UTC, paulo-granthon commented on api/src/main/java/com/khali/api3/repositories/Transactional.java
O que seria esse arquivo vazio?

2023-10-12 18:30 UTC, paulo-granthon commented on web/src/services/ProjectService.ts
> +        active: item.active? "Ativo" : "Inativo",
Aqui, ao mapear a boolean `active` pro front, podemos verificar se há uma `expire_date`
```suggestion
        active: item.expire_date? "Ativo" : "Inativo",
```

2023-10-12 21:08 UTC, Incivius commented on api/src/main/java/com/khali/api3/controllers/UserController.java
> +            // if (resultCenterService.findByGestorID(id).size() > 0) permissions.add(Permission.Validate);
@paulo-granthon Sim

2023-10-12 22:56 UTC, JhonatanLop commented on api/src/main/java/com/khali/api3/repositories/ProjectRepository.java
> +    int insertProject(@Param("name") String name, @Param("description") String description);
foi uma forma que encontramos de inserir os dados e manter os valores default no banco de dados.
Não está dessa forma em nenhuma outra parte do código.
Tentamos manter o padrão mas algo não estava dando certo apenas para Project.

2023-10-12 22:59 UTC, JhonatanLop commented on api/src/main/java/com/khali/api3/repositories/Transactional.java
ocorreu um erro ao importar uma biblioteca  e provavelmente esse arquivo foi criado por engano
o mesmo é desnecessário.

2023-10-12 23:06 UTC, Incivius reviewed
Aplicamos todas as sugestões de melhoria

2023-10-12 23:14 UTC, Incivius reviewed
Aceito

2023-10-12 23:24 UTC, paulo-granthon approved these changes

2023-10-13 00:19 UTC, taniacruzz approved these changes

2023-10-13 00:19 UTC, merged