Atualização de Banco de Dados
projetoKhali/api3 pull request #146
Opened 2023-10-13 14:55 UTC by JhonatanLop

# 🥳 Conclusão de tarefa <br>  
`Insira o #ID do(s) Issue(s) que essa entrega conclui no seguinte formato: "resolve #ID"`  

- resolve #138 
- resolve #106 

<br>

2023-10-13 19:53 UTC, taniacruzz commented
Arquivo DDL:
Incluir ENUM:

```
CREATE TYPE Periodo AS ENUM (
    'Noturno',
    'Diurno',
    'Indiferente'
);
```

Incluir as seguintes linhas após declaração dos ENUMs:
```
CREATE CAST (varchar AS apt_type) WITH INOUT AS IMPLICIT;
CREATE CAST (varchar AS periodo) WITH INOUT AS IMPLICIT;
```


Incluir tabela parameters (não usar check para inicio e fim da hora noturna, pois possivelmente o fim da hora noturna será menor que o início)
```
create table if not exists parameters(
    prm_id serial primary key,
    insert_date timestamp default now(),
    closing_day int,
    start_night_time time,
    end_night_time time
);
```

Alterações na classe pay_rate_rules (essa tabela ainda deverá ter a inclusão de dias da semana), que será feita pelo Paulo)
```
create table if not exists pay_rate_rules(
    prt_id serial primary key,
    code int unique not null,
    hour_duration numeric,
    pay_rate numeric,
    appointment_type Apt_type,
    periodo Periodo,
    overlap boolean,
    expire_date timestamp
);
```

2023-10-13 22:06 UTC, paulo-granthon commented
> Incluir as seguintes linhas após declaração dos ENUMs:
> 
> ```sql
> CREATE CAST (varchar AS apt_type) WITH INOUT AS IMPLICIT;
> CREATE CAST (varchar AS periodo) WITH INOUT AS IMPLICIT;
> ```

Será que não era isso que estava faltando pra tabela `appointments` para que os enums de `AppointmentType` e `AppointmentStatus` funcionassem corretamente?

2023-10-13 22:22 UTC, paulo-granthon requested changes

2023-10-13 22:22 UTC, paulo-granthon commented on api/sql/ddl/table.sql
>      'Employer',
`Employer` deve ser trocado para `Employee`. Essa modificação já havia sido comentada anteriormente, acho que esse PR seria um bom momento para incluí-la.

```suggestion
    'Employee',
```

2023-10-14 14:44 UTC, Incivius approved these changes

2023-10-14 15:08 UTC, Incivius approved these changes

2023-10-14 15:59 UTC, Incivius commented on api/sql/ddl/table.sql
> +CREATE TYPE Period AS ENUM (
Tentei rodar essa tabela e deu erro, a palavra "Period" é uma palavra reservada do Postgres, recomendo colocar "Period_type"

CREATE TYPE Period_type AS ENUM (
    'Nightime',
    'Daytime',
    'Allday'
);

2023-10-14 16:02 UTC, Incivius requested changes

2023-10-14 16:02 UTC, Incivius commented on api/sql/ddl/table.sql
> +    period Period,
periodo_type Periodo_type,

Ajustar aqui para se fazer referencia ao novo nome da tabela

2023-10-14 16:02 UTC, Incivius commented on api/sql/ddl/table.sql
>  create table if not exists projects(
Temos duas tabelas? Project e Projects?

2023-10-14 18:43 UTC, JhonatanLop commented
foi apagado a tabela duplicada e resolvido o problema do enum com nome reservado

2023-10-14 21:31 UTC, Incivius approved these changes

2023-10-14 21:37 UTC, taniacruzz approved these changes

2023-10-14 22:12 UTC, merged

2023-10-14 23:02 UTC, paulo-granthon commented on api/src/main/java/com/khali/api3/controllers/UserController.java
>      @PutMapping("/{id}/desactivate")
deactivate*