Visualização dos dados da tabela Appointment
projetoKhali/api3 pull request #147
Opened 2023-10-14 18:12 UTC by Incivius

# 🥳 Conclusão de tarefa <br>  
- Arrumei a forma com que algumas informações apareciam na tabela de appointments

2023-10-14 21:46 UTC, JhonatanLop approved these changes
bom

2023-10-14 22:59 UTC, paulo-granthon requested changes

2023-10-14 22:59 UTC, paulo-granthon commented on api/src/main/java/com/khali/api3/repositories/ResultCenterRepository.java
> +    public ResultCenter save(String resultCenter);
qual a motivação dessa mudança de `ResultCenter` para `String`?

2023-10-14 22:59 UTC, paulo-granthon commented on web/src/pages/Users.tsx
> +    : users.filter((user) => user.expiredDate === "N/A");
podemos reduzir a quantidade de operações se reescrevermos o filtro de seguinte forma:

```suggestion
    const filteredUsers = users.filter((user) => showDeactivated == (user.expiredDate !== "N/A"));
```

| showDeactivated | user.expiredDate !== "N/A" | resultado |
|---------------------------|----------------------------------------|---------------|
| true | true | true | 
| false | false | true |
| true | false | false |
| false | true | false |

- mostrar desativados && possui expireDate = inclui user
- ocultar desativados && não possui expireDate = inclui user
- mostrar desativados && não possui expireDate = não inclui user
- ocultar desativados && possui expireDate = não inclui user

2023-10-14 22:59 UTC, paulo-granthon commented on web/src/services/Access.ts
>              url:   'http://localhost:7000/Appointments' }
remover base da url pois será definida através de variaveis de ambiente
```suggestion
            url:   '/Appointments' }
```

2023-10-14 22:59 UTC, paulo-granthon commented on web/src/services/AppointmentService.ts
> +        user: item.user? item.user.name : -1,
campo não refere-se a um número então não faz sentido utilizarmos o valor `-1` como default
```suggestion
        user: item.user? item.user.name : "N/A",
```

2023-10-14 22:59 UTC, paulo-granthon commented on web/src/services/ProjectService.ts
> +        expireDate: item.expireDate? formatDateTime(item.expireDate) : "Em andamento...",
deve ser `"N/A"` para seguir o mesmo padrão dos outros schemas
```suggestion
        expireDate: item.expireDate? formatDateTime(item.expireDate) : "N/A",
```

2023-10-14 22:59 UTC, paulo-granthon commented on web/src/services/UserService.ts
> +}
a função possui um nome genérico para uma operação específica, o nome `PUT` implica que podemos efetuar qualquer tipo de atualização no usuário sendo que a função é responsável apenas por atualizar o "status ativo" do usuário (ativar / desativar).

aqui está uma sugestão de como refatorar a função para reduzir repetição de código e melhorar a clareza

```suggestion
export async function updateUserActiveStatus(user: UserSchema, newActiveStatus: boolean) {
    let response = null;
    let endpoint = newActiveStatus ? 'activate' : 'deactivate';

    try {
            response = await fetch(`${API_URL}/${user.id}/${endpoint}`, {
                method: 'PUT',
                headers: {
                    "Content-Type": 'application/json'
                },
                body: JSON.stringify(user)
            });
        }
        if (!response || !response.ok) {
            throw new Error(`Erro ao atualizar o usuário: ${response ? response.statusText : 'Resposta não recebida'}`);
        }
        return response.json();
    } catch (error) {
        console.error("Erro ao atualizar o usuário:", error);
        throw error;
    }
}
```

2023-10-14 22:59 UTC, paulo-granthon commented on web/src/pages/Users.tsx
> +    };
podemos utilizar a mesma função para fazer as duas operações, basta incluirmos uma boolean como parametro assim como na função "putUser".

também sugiro alterar o nome da função `putUser` para `updateUserActiveStatus` em um outro comentário por questões de legibilidade e entendimento do código.

além disso, não precisamos construir um segundo `UserSchema` para fazer essa alteração.

```suggestion
    const handleChangeUserActiveStatus = (userId: number, newActiveStatus: boolean) => {
        const operation = newActiveStatus ? 'ativar' : 'desativar';
        const confirmResult = window.confirm('Tem certeza de que deseja ${operation} este usuário?');
        if (confirmResult) {
            updateUserActiveStatus(userId, newActiveStatus)
                .then((updatedUser) => {
                    if (updatedUser) {
                        requestUsers();
                    }
                })
                .catch((error) => {
                    console.error('Erro ao ativar o usuário:', error);
                });
        }
    };
```

2023-10-14 22:59 UTC, paulo-granthon commented on web/src/pages/Users.tsx
> +                    <button onClick={() => handleDeactivateUser(data)}>Desativar</button>
aqui podemos utilizar então:
```suggestion
                    <button onClick={() => handleChangeUserActiveStatus(data.id, true)}>Ativar</button>
                ) : (
                    <button onClick={() => handleChangeUserActiveStatus(data.id, false)}>Desativar</button>
```

2023-10-15 17:21 UTC, taniacruzz approved these changes

2023-10-15 18:18 UTC, paulo-granthon approved these changes

2023-10-15 18:26 UTC, merged