Atualização de Insert e Get de Projetos
projetoKhali/api3 pull request #148
Opened 2023-10-14 19:50 UTC by JhonatanLop

# 🥳 Conclusão de tarefa <br>  
`Insira o #ID do(s) Issue(s) que essa entrega conclui no seguinte formato: "resolve #ID"`  

- resolve #104 
- resolve #102 

<br>

# 🚀 Extras <br>  
`Essa entrega inclui alguma feature extra concluída ou em progress? Cite-a(s)`

- trazendo todos os projetos ativos
- inserindo projetos com dados default no banco.

<br>

2023-10-14 22:19 UTC, paulo-granthon requested changes

2023-10-14 22:19 UTC, paulo-granthon commented on api/src/main/java/com/khali/api3/domain/user/User.java
>      @Column(name = "insert_date")
falta adicionar `@Transient` ao `insert_date` de `User`
```suggestion
    @Transient
    @Column(name = "insert_date")
```
favor verificar também as outras classes para a inserção do `@Transient`

2023-10-15 20:35 UTC, JhonatanLop commented on api/src/main/java/com/khali/api3/domain/user/User.java
>      @Column(name = "insert_date")
esse ajuste já foi resolvido no branch `user_controller`

2023-10-16 02:37 UTC, paulo-granthon approved these changes

2023-10-16 02:38 UTC, Incivius approved these changes

2023-10-16 02:41 UTC, merged