Atualização de método para desabilitar usuário
projetoKhali/api3 pull request #151
Opened 2023-10-14 21:39 UTC by JhonatanLop

# 🥳 Conclusão de tarefa <br>  
`Insira o #ID do(s) Issue(s) que essa entrega conclui no seguinte formato: "resolve #ID"`  

Complementa issue
- #131 

<br>

# 🚀 Extras <br>  
`Essa entrega inclui alguma feature extra concluída ou em progress? Cite-a(s)`

 desativa a relação usuário x centro de resultado "members"

<br>

# 🏅 Comentários adicionais <br>  
`Algo mais que gostaria de comentar com a equipe a respeito da entrega dessa tarefa?`

foi inserido uma coluna nova na tabela members e adicionado novos métodos na classe MembersRepository

<br>

2023-10-14 22:15 UTC, paulo-granthon requested changes

2023-10-14 22:15 UTC, paulo-granthon commented on api/src/main/java/com/khali/api3/controllers/UserController.java
> +            if (user.getUserType().equals(UserType.Admin)) {
usa-se `.equals` em vez de `==` mesmo? Se não me engano tinha perguntado ao @Incivius sobre esse ponto e a conclusão era que deveriamos usar o `==`.
Confirma se da forma que está nesse PR, a comparação de enum functiona?

2023-10-14 22:15 UTC, paulo-granthon commented on api/src/main/java/com/khali/api3/domain/member/Member.java
> +    boolean active;
devemos utilizar `expire_date` no lugar de `active`

2023-10-14 22:15 UTC, paulo-granthon commented on api/src/main/java/com/khali/api3/services/MembersService.java
> +    }
seguindo a utilização de `expire_date`.
ao desativar: um valor é associado ao `expire_date`;
ao ativar: `expire_date` se torna null.

2023-10-14 22:15 UTC, paulo-granthon commented on api/src/main/java/com/khali/api3/services/MembersService.java
> +        Member member = new Member(memberPK, true, null);
não é necessário passar explicitamente todos os valores do Vconstrutor de `Member` pois o mesmo contém a `@NoArgsConstructor`
```suggestion
        Member member = new Member();
        member.setMemberPK(memberPK);
```
dessa forma, criamos o `Member` com todos os campos com valor `null` e apenas associamos um valor ao `memberPK`

2023-10-15 13:31 UTC, JhonatanLop commented on api/src/main/java/com/khali/api3/controllers/UserController.java
> +            if (user.getUserType().equals(UserType.Admin)) {
essa alteração veio de um merge que puxei ou já estava antes de eu fazer as modificações.
Já q foi confirmado que == funciona melhor que .equals() irei fazer a alteração

2023-10-15 13:34 UTC, JhonatanLop commented on api/src/main/java/com/khali/api3/domain/member/Member.java
> +    boolean active;
nessa tabela específica não existe a necessidade de um expire_date já que será o mesmo do usuário e as relações estão conectadas com esse usuário.
Optei também por guardar um valor booleano ao invés de um tipo timestamp para economizar memória. já que no nosso sistema nada é apagado e sim desativado

2023-10-15 15:35 UTC, paulo-granthon commented on api/src/main/java/com/khali/api3/domain/member/Member.java
> +    boolean active;
show, tem razão

2023-10-15 17:35 UTC, paulo-granthon approved these changes

2023-10-16 02:37 UTC, paulo-granthon approved these changes

2023-10-16 02:38 UTC, Incivius approved these changes

2023-10-16 02:41 UTC, merged