refactor: Atualização de apontamento
projetoKhali/api3 pull request #170
Opened 2023-10-21 01:27 UTC by JhonatanLop

# 🥳 Conclusão de tarefa <br>  
`Insira o #ID do(s) Issue(s) que essa entrega conclui no seguinte formato: "resolve #ID"`  

- resolve #112 

<br>

# 🏅 Comentários adicionais <br>  
`Algo mais que gostaria de comentar com a equipe a respeito da entrega dessa tarefa?`

esse método recebe o id de um apontamento e o corpo de outro apontamento que seria o apontamento atualizado.
o código desativa o apontamento antigo, pega o id dela e adiciona no apontamento novo na coluna apt_updt.

<br>

2023-10-21 01:33 UTC, paulo-granthon requested changes

2023-10-21 01:33 UTC, paulo-granthon commented on api/sql/ddl/table.sql
> +    active BOOLEAN DEFAULT TRUE,
qual seria o motivo do retorno da boolean active em vez de utilizar o `expire_date`?

2023-10-21 01:33 UTC, paulo-granthon commented on api/src/main/java/com/khali/api3/controllers/AppointmentController.java
>      }
Ao fazer essa alteração, trocamos o retorno da função `getAll`, que talvez seja utilizada futuramente esperando o retorno atual.
Em vez disso, podemos criar uma nova função com uma rota diferente que retorna apenas os ativos

2023-10-21 01:33 UTC, paulo-granthon commented on api/src/main/java/com/khali/api3/domain/appointment/Appointment.java
> +    @Transient
devemos abandonar o uso da anotação `@Transient` nos casos em que estão sendo utilizadas na nossa codebase, veja o issue #168

2023-10-21 01:33 UTC, paulo-granthon commented on api/src/main/java/com/khali/api3/repositories/AppointmentRepository.java
> +
```suggestion

```

2023-10-21 01:34 UTC, paulo-granthon commented on api/src/main/java/com/khali/api3/domain/appointment/Appointment.java
> +    @Transient
resolvida no commit [87b41bd](https://github.com/projetoKhali/api3/pull/170/commits/87b41bd453cb8979e522cc1c20f3215bed5bda2f) :+1:

2023-10-25 00:54 UTC, JhonatanLop commented on api/sql/ddl/table.sql
> +    active BOOLEAN DEFAULT TRUE,
com o insertdate do apontamento atualizado já temos o expiredate do apontamento antigo.

2023-10-25 00:56 UTC, JhonatanLop commented on api/src/main/java/com/khali/api3/controllers/AppointmentController.java
>      }
apontamentos antigos não devem aparecer com os atualizados, visto que isso pode acabar causando confusão no usuário.
em nenhuma situação os ambos os apontamentos deverão aparecer ao mesmo tempo

2023-10-25 01:35 UTC, paulo-granthon commented on api/sql/ddl/table.sql
> +    active BOOLEAN DEFAULT TRUE,
então também não precisamos de `active`, apenas o `apt_updt_id` já serve

2023-10-25 13:42 UTC, paulo-granthon approved these changes

2023-10-25 22:44 UTC, taniacruzz approved these changes

2023-10-27 00:19 UTC, merged