feat: Implementação da classe Squad
projetoKhali/api3 pull request #30
Opened 2023-09-08 20:21 UTC by Incivius

# 🥳 Conclusão de tarefa <br>  
- resolve #17

<br>

2023-09-08 20:51 UTC, Incivius commented
Vou aguardar a resolução da tarefa #18 para seguir com a criação do método "Get" do endpoint /Squad

2023-09-09 12:19 UTC, paulo-granthon requested changes

2023-09-09 12:19 UTC, paulo-granthon commented on api/src/main/java/com/khali/api3/domain/squad/Squad.java
> +    private int managerId;
marcando para revisão

2023-09-13 16:00 UTC, paulo-granthon approved these changes

2023-09-14 01:47 UTC, closed without merging