Merge pull request #14 from projetoKhali/ERD
projetoKhali/api3 pull request #32
Opened 2023-09-12 14:08 UTC by MikaelaBgtt

# 🥳 Conclusão de tarefa <br>  
`resolve #14"`  

- resolve #

<br>

# 🚀 Extras <br>  
`Apenas criação de FKs que faltavam e edição de campos/sintaxe.`

<br>

2023-09-12 18:32 UTC, paulo-granthon commented
![2023_09_12_15:31:09_sshot](https://github.com/projetoKhali/api3/assets/93501477/38941f0d-5d22-40ff-a6ea-014f6bcf1f48)
faltou colocar `web/node_modules` no .gitignore

2023-09-13 22:37 UTC, paulo-granthon approved these changes

2023-09-17 14:51 UTC, JhonatanLop requested changes

2023-09-17 14:51 UTC, JhonatanLop commented on api/sql/ddl/table.sql
> +alter table appointments alter column insert_date set default(CURRENT_TIMESTAMP);
esses alter tables não são mais necessários, a tabela já tem as configurações atualizadas

2023-09-17 14:51 UTC, JhonatanLop commented on api/src/main/java/com/khali/api3/domain/appointment/Appointment.java
>  @Entity(name="appointments")
falta adicionar a anotação JPA com o nome da tabela

2023-09-17 14:51 UTC, JhonatanLop commented on api/sql/ddl/table.sql
> +alter table users alter column insert_date set default(CURRENT_TIMESTAMP);
```suggestion
```

2023-09-17 14:51 UTC, JhonatanLop commented on api/sql/ddl/table.sql
> +alter table appointments alter column insert_date set default(CURRENT_TIMESTAMP);
```suggestion
```

2023-09-17 17:10 UTC, JhonatanLop approved these changes
Nice work

2023-09-17 22:56 UTC, paulo-granthon approved these changes

2023-09-24 15:55 UTC, merged